AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: "Create resources for AWS Devtools"

Resources: 
  CommonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'common.yaml'

  DevtoolsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CommonStack
    Properties:
      TemplateURL: "../pipeline/mlops-devtools.yaml"

  DeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DevtoolsStack
    Properties:
      TemplateURL: "../deploy/mlops-deploy.yaml"