AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: "Create resources for AWS Sagemaker Pipelines"

Resources: 
  CommonStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'common.yaml'

  SageMakerPipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CommonStack
    Properties:
      TemplateURL: "../sgPipeline/mlops-sagemaker-pipeline.yaml"
  
  DeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SageMakerPipelineStack
    Properties:
      TemplateURL: "../deploy/mlops-deploy.yaml"
