version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Updating Packages...
      - pip install --upgrade --force-reinstall botocore boto3 awscli
  build:
    commands:
      - echo Build started on `date`
      - echo Configuring CloudFormation Parameters for $STAGE Deployment...
      - |
        sh -c """
        python build.py --pipeline-name=$PIPELINE_NAME \
                        --import-config=$CODEBUILD_SRC_DIR/$STAGE/$STAGE-config.json \
                        --export-config=$CODEBUILD_SRC_DIR/$STAGE/$STAGE-config-export.json
        """
      - echo CloudFormation Parameters...
      - cat $CODEBUILD_SRC_DIR/$STAGE/$STAGE-config-export.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - $STAGE/$STAGE-config-export.json
    - $STAGE/deploy-model-$STAGE.yaml
  discard-paths: yes