AWSTemplateFormatVersion: 2010-09-09

Description: Deploy a model to Sagemaker for QA Hosting

Parameters:

  ModelName:
    Type: String
    Description: Name of the model.

  ModelPackageName:
    Type: String
    Description: The trained Model Package Name.

Resources:

  Model:
    Type: AWS::SageMaker::Model
    Properties:
      PrimaryContainer:
        ModelPackageName: !Ref ModelPackageName
      ExecutionRoleArn: !ImportValue MLOpsDeployRole

  EndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
      - ModelName: !GetAtt Model.ModelName
        VariantName: AllTraffic
        InitialVariantWeight: 1.0
        ServerlessConfig:
          MaxConcurrency: 20
          MemorySizeInMB: 1024

  Endpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName:
        Fn::Join:
          - "-"
          - - Fn::ImportValue: MLOpsPipelineName
            - "qa" 
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
    DependsOn: EndpointConfig

Outputs:
  QAEndpointName:
    Description: "Endpoint Name"
    Value: !GetAtt Endpoint.EndpointName